server:
  port: 8087
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
  elasticsearch:
    rest:
      uris: http://47.102.204.189:9200
  rabbitmq:
    host: 47.102.204.189
    username: zl
    password: lz.com
    virtual-host: /
